--=================== таблица Пользователи
 CREATE TABLE IF NOT EXISTS users (
              user_Id 		INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name		VARCHAR(100),
              email 	VARCHAR(100) NOT NULL,
			  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
          );
COMMENT ON TABLE users IS 'Таблица хранит данные о пользователях';
COMMENT ON COLUMN users.user_Id IS 'Уникальный идентификатор пользователя, первичный ключ';
COMMENT ON COLUMN users.name IS 'Имя';
COMMENT ON COLUMN users.email IS 'Электронная почта';
 
--=================== таблица Фильмы
 CREATE TABLE IF NOT EXISTS items (
              id 				INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              owner_id			INTEGER REFERENCES users (user_Id) ON DELETE RESTRICT,
              name 	    		VARCHAR(100),
              description 		VARCHAR(200),
              available 		BOOLEAN
          );
COMMENT ON TABLE items IS 'Таблица хранит данные о вещах';
COMMENT ON COLUMN items.id IS 'Уникальный идентификатор вещи, первичный ключ';
COMMENT ON COLUMN items.owner_id IS 'Владелец вещи, ссылка на объект таблицы users';
COMMENT ON COLUMN items.name IS 'Название вещи';
COMMENT ON COLUMN items.description IS 'Описание вещи';
COMMENT ON COLUMN items.available IS 'Доступность, True - доступна, False - не доступна';

--=================== очищение данных
DELETE FROM items;
DELETE FROM users;