--=================== таблица Пользователи
 CREATE TABLE IF NOT EXISTS users (
              user_Id 		INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name		VARCHAR(100),
              email 	VARCHAR(100) NOT NULL,
			  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
          );
COMMENT ON TABLE users IS 'Таблица хранит данные о пользователях';
COMMENT ON COLUMN users.user_Id IS 'Уникальный идентификатор пользователя, первичный ключ';
COMMENT ON COLUMN users.name IS 'Имя';
COMMENT ON COLUMN users.email IS 'Электронная почта';
 
--=================== таблица Вещи
 CREATE TABLE IF NOT EXISTS items (
              id 				INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              owner_id			INTEGER REFERENCES users (user_Id) ON DELETE RESTRICT,
              name 	    		VARCHAR(100),
              description 		VARCHAR(200),
              available 		BOOLEAN
          );
COMMENT ON TABLE items IS 'Таблица хранит данные о вещах';
COMMENT ON COLUMN items.id IS 'Уникальный идентификатор вещи, первичный ключ';
COMMENT ON COLUMN items.owner_id IS 'Владелец вещи, ссылка на объект таблицы users';
COMMENT ON COLUMN items.name IS 'Название вещи';
COMMENT ON COLUMN items.description IS 'Описание вещи';
COMMENT ON COLUMN items.available IS 'Доступность, True - доступна, False - не доступна';

--=================== таблица Бронирования
 CREATE TABLE IF NOT EXISTS bookings (
              id 			INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              renter_id		INTEGER REFERENCES users (user_Id) ON DELETE RESTRICT,
              item_id		INTEGER REFERENCES items (id) ON DELETE RESTRICT,
              booking_start_datetime TIMESTAMP,
              booking_end_datetime TIMESTAMP,
              status 		VARCHAR(100)
          );
COMMENT ON TABLE bookings IS 'Таблица хранит данные о бронированиях';
COMMENT ON COLUMN bookings.id IS 'Уникальный идентификатор бронирования';
COMMENT ON COLUMN bookings.renter_id IS 'Идентификатор пользователя-арендатора вещи';
COMMENT ON COLUMN bookings.item_id IS 'Идентификатор бронируемой вещи';
COMMENT ON COLUMN bookings.booking_start_datetime IS 'Дата и время начала брони';
COMMENT ON COLUMN bookings.booking_end_datetime IS 'Дата и время окончания брони';
COMMENT ON COLUMN bookings.status IS 'Статус брони';

--=================== таблица Отзывы
 CREATE TABLE IF NOT EXISTS comments (
              id 			INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              item_id		INTEGER REFERENCES items (id) ON DELETE RESTRICT,
              author_id		INTEGER REFERENCES users (user_Id) ON DELETE RESTRICT,
              text 		    VARCHAR(1000),
              creation_date TIMESTAMP
          );
COMMENT ON TABLE comments IS 'Таблица хранит отзывы о вещах';
COMMENT ON COLUMN comments.id IS 'Уникальный идентификатор отзыва';
COMMENT ON COLUMN comments.author_id IS 'Идентификатор пользователя-автора';
COMMENT ON COLUMN comments.item_id IS 'Идентификатор вещи';
COMMENT ON COLUMN comments.text IS 'Текст отзыва';
COMMENT ON COLUMN comments.creation_date IS 'Дата и время создания отзыва';

--=================== очищение данных на случай наличия в них старых тестовых данных
DELETE FROM comments;
DELETE FROM bookings;
DELETE FROM items;
DELETE FROM users;